repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        
  - repo: local
    hooks:
      - id: pytest-fast
        name: Run fast unit tests
        entry: uv run pytest
        language: system
        args: [tests/unit/, -x, --tb=short, -q, -m, "not slow"]
        pass_filenames: false
        always_run: true