# Ruff configuration for special education policy analysis project

# Same as Black
line-length = 100
target-version = "py312"

# Exclude a variety of commonly ignored directories
exclude = [
    ".bzr",
    ".direnv", 
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[lint]
# Enable pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default
select = [
    "E9",   # pycodestyle error codes
    "F",    # Pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
]

# Allow autofix for all enabled rules (when `--fix`) is provided
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
# Tests can use magic values, assertions, and unused imports
"tests/*" = ["E501", "S101", "F401", "F811"]
"src/**/tests/*" = ["E501", "F401", "F811"]

[lint.mccabe]
max-complexity = 10

[format]
# Use double quotes for strings
quote-style = "double"

# Use 4 spaces for indentation
indent-style = "space"

# Respect magic trailing commas
skip-magic-trailing-comma = false

# Automatically detect line ending format
line-ending = "auto"
