name: Feature Request
description: Suggest an idea or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this valuable? What problem does it solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Outline of approach, scope, and acceptance criteria
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: textarea
    id: testing
    attributes:
      label: Testing & Validation
      description: How should we test and validate this change?

